### ISSUE TITLE
rgb value above 1

### ISSUE THREAD

**Issue by TheoHiwo** [hsluv/hsluv-javascript#3]
Hi, do need to be concerned about negligible decimals above 1 for rgb?
   ```
 var conv = new Hsluv();
conv.hsluv_h = h;
conv.hsluv_s = s;
conv.hsluv_l = l;
conv.hsluvToRgb();
const rgb = conv
console.log(rgb)
```
![image](https://user-images.githubusercontent.com/35316996/202857422-54056b91-c8b8-4043-b4da-5d63a90eb5de.png)

**Comment by boronine** [comment]
Discussed previously: https://github.com/hsluv/hsluv-python/issues/7

Basically these are just artifacts of floating point math, you don't need to worry about them, but depending on your code you may need to clamp the values to 0-1 range. Adding this to our code is a bit debatable, because floating point numbers shouldn't be interpreted as exact anyways, and clamping probably exacerbates floating point error if done in the middle of a calculation.
